export const REALTIME_WORKING_AGENT_EXECUTION_MAX = 32;
export const REALTIME_MAX_FRAME_BYTES = 65_536;
export const REALTIME_MAX_PENDING_CONTROLS = 16;
export const REALTIME_MAX_REFS = 1_000_000;
export const REALTIME_MAX_IDENTITY_BYTES = 256;
export const PHOENIX_MANUAL_TIMER_MS = 2_147_483_647;
